title: Simple CSPM

url: https://somethingnew2-0.github.io/

remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: dark

ga_tracking: UA-210888102-2
ga_tracking_anonymize_ip: true

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/somethingnew2-0/SimpleCSPM" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "edit"

aux_links:
  "SimpleCSPM on GitHub":
    - "//github.com/somethingnew2-0/SimpleCSPM"
aux_links_new_tab: true
